root: "/media/data/toyota/processed_data/trina_33_final/"
token_root: "/media/data/toyota/processed_data/trina_33_samples_wdrive/"

train_tasks: ["I", "M", "S"]
test_tasks: ["I", "M", "S"]
modalities: ["ECG", "EDA", "RSP", "SKT"]

scale: 1
permute: 0
use_shap: 1
seed: 79911092