root: "/media/data/toyota/processed_data/trina_33/"
proc_root: "/media/data/toyota/processed_data/trina_33_samples_fupd/"
device: cuda  # cuda or cpu
n_splits: 5
test_size: 0.2
batch_size: 64
num_workers: 16
shuffle: True
tasks: ["I"]
modalities: ["ecg", "eda", "rsp"]

model_config:
  in_channels: 1
  base_filters: 32
  n_block: 4
  n_classes: 2

lr: 0.0005
step_size: 5

load_from: null
early_stopping: True
patience: 5
max_epochs: 50